# reload can reset rr servers when files change
reload:
  # refresh interval (default 1s)
  interval: 1s

  # file extensions to watch, defaults to [.php]
  patterns: [".php"]

  # list of services to watch
  services:
    http:
      # list of dirs, "" root
      dirs: [""]

      # include sub directories
      recursive: true
# http service configuration.
http:
  reset: true
  address: 0.0.0.0:8080

  workers:
    command: "php app.php"
    pool:
      numWorkers: 40

# queue and jobs
jobs:
  dispatch:
    app-job-*.pipeline: "local"
  pipelines:
    local:
      broker: "ephemeral"
  consume: ["local"]

  workers:
    command: "php app.php"
    pool.numWorkers: 100
    pool.maxJobs:    100

# serve static files
static:
  dir:    "public"
  forbid: [".php", ".htaccess"]

metrics:
  # prometheus client address (path /metrics added automatically)
  address: localhost:2112

# control the max memory usage
limit:
  services:
    http.maxMemory: 100
    jobs.maxMemory: 100
    grpc.maxMemory: 100

grpc:
  listen: tcp://0.0.0.0:50051
  workers.command: "php app.php"

  # read how to write proto files in the next section
  proto: "proto/service.proto"

  # tls configuration is optional
  # tls.key:  "app.key"
  # tls.cert: "app.crt"